server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: backend
          uri: http://localhost:8080
          predicates:
            - Path=/roses/**, /flowers/**, /tulips/**, /gypsophilas/**
        - id: backend-subdomain
          uri: http://localhost:8083
          predicates:
            - Path=/customers/**, /cartItems/**
        - id: frontend-subdomain
          uri: http://localhost:8082
          predicates:
            - Path=/shop/**, /shop/js/**
        - id: frontend
          uri: http://localhost:8081
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: BoundedContext576
          uri: http://BoundedContext576:8080
          predicates:
            - Path= 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080